service: memo
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1
  logRetentionInDays: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  get:
    handler: index.get
    events:
      - http:
          path: /
          method: get
          request:
            parameters:
              querystrings:
                q: true
  post:
    handler: index.post
    events:
      - http:
          path: /
          method: post
          request:
            parameters:
              querystrings:
                q: true

resources:
  Resources:
    DocumentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: documents
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: TimeToLive
          Enabled: true
